### ISSUE TITLE
slim_extract_genlight errors with ploidy

### ISSUE THREAD

**Issue by PetaLHill** [rdinnager/slimr#60]
Hey Russell,
as per my email, the genlight object that results from the above has ploidy issues. I looked a bit more at it today and gl@ploidy results in "NULL" but when I look at ploidy for each individual, it's either 1,2,or 3. The 3's probably come from the stacking policy as you mentioned, I'm not sure about the 1's. setting ploidy to 2 allows further downstream analysis but I do wonder what this is doing to the genotypes inside the genlight object itself. Anyway, thanks for your help!
Peta

**Comment by rdinnager** [comment]
This should be fixed. Let me know if you still see this after installing the latest version.
