### ISSUE TITLE
slim_extract_genlight issues

### ISSUE THREAD

**Issue by PetaLHill** [rdinnager/slimr#61]
Hi Russell,
when extracting data into a genlight object there are some slots in the @other that functions in the dartr package don't like. Bernd wrote a workaround for me so we can use various dartr functions to analyse our genlight objects:
ot <- as.data.frame(gl@other)
gl@other<-list()
gl <- gl.compliance.check(gl,verbose = 0)
gl@other$loc.metrics$mut_type <- ot$mut_type
gl@other$loc.metrics$prevalence <- ot$prevalence

I wonder if this could be added into the slim_extract_genlight function?
ps Bernd says "Hi"
:-)

**Comment by rdinnager** [comment]
I think a bug fix for another issue ended up fixing this issue. If it crops up again, please reopen this issue.
