### ISSUE TITLE
`if() {} else {}` construction failing

### ISSUE THREAD

**Issue by rdinnager** [rdinnager/slimr#62]
A bug has been introduced at some point that is causing if else statements to not be parsed correctly. A newline is being inserted between the `if` block and the `else` which is incorrect syntax for R and so it can't be parsed correctly. This used to work so it must be a regression introduced at some point.

**Comment by jannafierst** [comment]
Hey Russell - I'm having issues with this too, actually with this non-standard SLiM-type if else construction

insCount1 = tes1.size() ? rpois(1, (1 - abar)^2 * u) else 0;

Were you able to fix this? Thanks!
